### ISSUE TITLE
Website dump support

### ISSUE THREAD

**Issue by zerjioang** [pipermerriam/ethereum-function-signature-registry#106]
I just find the initiative of the website https://www.4byte.directory/ while researching about eth security and realize there is no way to fetch a copy of the database for offline lookup. I wonder if you are planning to provide some sort of weekly backup dumps, like Wikimedia does (https://dumps.wikimedia.org/backup-index.html). If not, would you agree if I build and release a crawler for your current version of the API?

**Comment by ligi** [comment]
This might be what you need: https://github.com/ethereum-lists/4bytes

**Comment by zerjioang** [comment]
@ligi thats look great. I think I can start prototyping with that. Just one question: is that the content behind 4bytes.directory or those files of that github repo are taken from other sources?

**Comment by ligi** [comment]
another big source for the repo is sourcify - so has over 100k more signatures

**Comment by zerjioang** [comment]
@ligi thats look interesting. I think I can start prototyping with that. However integrating such big collection of files into an application could be a bit messy...any improvement ideas expected?

**Comment by ligi** [comment]
you can also pump it in a database easily if you want.

**Comment by zerjioang** [comment]
ok then. i can close the issue for now
