### ISSUE TITLE
Signature beginning with double-zero

### ISSUE THREAD

**Issue by evertonfraga** [pipermerriam/ethereum-function-signature-registry#11]
Hi Piper, I was investigating some edge cases here alongside with Avsa.

It seems that signature's bytecode initiated in "0x00" ends up as only "0x", as seen [in your Gist](https://gist.github.com/pipermerriam/79429c2163969ff732d5f2aabaaaf0e5#file-signatures-pretty-json-L4775).
```
  "0x": [
    "setLowerFeePercentage(uint8)",
    "setHand(uint256)",
    "comparisonchr(string)",
    "getTokenDivisor()",
    "getFrontend()",
    "triggerPayment()",
    "setMinimumPassPercentage(uint8)"
  ],
```

I cannot ensure the "0x00~" is the root cause, but I'm tending to believe in that :)

```
00873367 => comparisonchr(string)
00c721ab => setHand(uint256)
003b9d88 => setLowerFeePercentage(uint8)
```

**Comment by pipermerriam** [comment]
Well, I'm able to reproduce the bug now.  It's related to the django ORM and doesn't present itself when using `sqlite`.

https://github.com/pipermerriam/ethereum-function-signature-registry/pull/12

**Comment by pipermerriam** [comment]
Fix for this going out here in a few minutes when I confirm everything is still working as expected.  This will also fix all the *wrong* values that are currently in the database.

**Comment by evertonfraga** [comment]
@pipermerriam awesome.

**Comment by pipermerriam** [comment]
This is fixed and I *think* that all of the data is now correct.
