### ISSUE TITLE
Signature Database API returning 502s

### ISSUE THREAD

**Issue by KidA001** [pipermerriam/ethereum-function-signature-registry#122]
* OS: n/a
* Python version: n/a
* Environment: n/a

### What is wrong?

I am using the Signature Database API to get signatures. We repeatedly use it but cache any responses for signature's we've already requested for performance but also so we are not constantly hitting your servers.

We are often seeing 502's returned when we make a request, but seconds later we'll get a 200. Is there rate-limiting happening or are the server just overloaded? Is there a better way to interact with this endpoint?

**Comment by pipermerriam** [comment]
Very likely it's just overloaded.  It has been consistently getting hit with 40+ requests per second (up from the mid 20's a year or so ago).

**Comment by pipermerriam** [comment]
I've increased the number of cores on the box to 6 (up from 4).  Server is back up and seems to be happy again.

**Comment by KidA001** [comment]
Thank you! Appreciate that @pipermerriam !

I'm still getting some 502's - Is there a way to help contribute to the project financially to cover more server resources?
