### ISSUE TITLE
Possible dirty data on 4byte

### ISSUE THREAD

**Issue by evertonfraga** [pipermerriam/ethereum-function-signature-registry#19]
Hi @pipermerriam, i've got some entries from the API which doesn't seem to comply with the standard. I've omitted those on Mist embedded signature dictionary until further notice.

Thanks

```
"0xc72b4e60": [
        "setIpfsHash(bytes ipfsHash)"
],
"0x27fbe7fe": [
        "function setIpfsHash(bytes ipfsHash)"
],
"0x1e25c4a2": [
    "0x337b1cf9"
],
```

**Comment by pipermerriam** [comment]
I'm closing this issue as I have #13 open for tracking this same issue.  I'll try to get this figured out sooner than later.  Thanks for the reminder.

**Comment by evertonfraga** [comment]
Sure, and sorry for being distracted on this matter.

**Comment by pipermerriam** [comment]
Completely the opposite.  This has been back-burnered for a long time and this got me to futz with it some today and *maybe* get a fix in for this and some other issues that have been languishing.
