### ISSUE TITLE
normalize_function_signature() misbehaves when function name contains a Solidity type

### ISSUE THREAD

**Issue by smarx** [pipermerriam/ethereum-function-signature-registry#31]
https://github.com/pipermerriam/ethereum-function-signature-registry/blob/99d5cbe0d034f6590dd6a2f904323e4ca3e11f4f/func_sig_registry/utils/solidity.py#L140 applies the regular expression here: https://github.com/pipermerriam/ethereum-function-signature-registry/blob/99d5cbe0d034f6590dd6a2f904323e4ca3e11f4f/func_sig_registry/utils/solidity.py#L127-L135 to the entire submitted signature, including the function name.

This caused me problems when trying to submit signatures with the function name `mint` (which includes the string "int").

`mint(uint256 nonce, bytes32 challenge_digest)` was misinterpreted as `mint(int256,uint256,bytes32)`.

`mint(address _to, uint256 _amount)` failed with a 500. (My guess is that it's already been submitted.)

**Comment by holiman** [comment]
Yup, see also https://github.com/pipermerriam/ethereum-function-signature-registry/issues/30

**Comment by pipermerriam** [comment]
Should be resolved.
