### ISSUE TITLE
www.4byte.directory website down

### ISSUE THREAD

**Issue by justinludwig** [pipermerriam/ethereum-function-signature-registry#34]
Hi, thanks for this useful project! Looks like the website at https://www.4byte.directory/ is currently down -- I get an SSL cert error when I try to access it, and a "no such app" error from heroku when I try to access it via HTTP instead of HTTPS.

**Comment by pipermerriam** [comment]
Looks like the card on my heroku account expired and I never noticed, I'll get it back up and running later tonight or tomorrow.

**Comment by ligi** [comment]
@justinludwig in the meantime you can also use: https://github.com/ethereum-lists/4bytes

**Comment by pipermerriam** [comment]
Back up.
