### ISSUE TITLE
https://www.4byte.directory/submit: Server Error (500) when entering hex number

### ISSUE THREAD

**Issue by gpersoon** [pipermerriam/ethereum-function-signature-registry#36]
I inadvertently tried to enter a hex signature via https://www.4byte.directory/submit
(for example 0x12345678)
Then I got the error : Server Error (500)

Later i realized i should have entered the function, but i was confused for a while.
If would help if the description was more clear and/or an appropriate error message is given.

**Comment by pipermerriam** [comment]
I believe this is the correct place to start if someone wants to work on this

https://github.com/pipermerriam/ethereum-function-signature-registry/blob/def6c03daea61c4fdb7c159bb236997aa3f2672b/func_sig_registry/registry/views.py#L85-L97
