### ISSUE TITLE
server error when submitting function with array of a tuple

### ISSUE THREAD

**Issue by ligi** [pipermerriam/ethereum-function-signature-registry#37]
when trying to submit:

`getOrdersInfo((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes)[])`

the 4byte.direcory - I get a 500 server error

this is a valid signature

**Comment by kolinko** [comment]
... which is a function from:
0x4F833a24e1f95D70F028921e27040Ca56E09AB0b (zrx contract)

alternate signature:
getOrdersInfo(tuple[] _orders)

it breaks with tuple arrays in general.

a proper 4-byte representation for this is:  0x7e9d74dc (you can easily check it on https://eveem.org/json/0x4F833a24e1f95D70F028921e27040Ca56E09AB0b )

**Comment by pipermerriam** [comment]
I don't think tuple types formally existed when I first wrote this so some work would need to be done to formally support them.  A start would be for someone to come up with some test cases.

**Comment by kolinko** [comment]
Yeah, they are a new thing. Zrx contract & it's ABI is a good test case, I also have a parser for it that's been well tested - will post it tomorrow.

**Comment by ligi** [comment]
@pipermerriam you can test with these real world signatures:

those can build test-cases for this issue and #39 
```
setupDirectDebit(address,(uint256,uint256,uint256))
Forge(address,uint256,(uint32,uint8,uint8,uint8,uint8,uint32,uint32,uint32,uint32))
batchCancelOrders((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes)[])
EscrowStarted(bytes20,(bool,address,address,uint256))
batchFillOrdersNoThrow((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes)[],uint256[],bytes[])
fillOrKillOrder((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes),uint256,bytes)
EscrowReleased(bytes20,(bool,address,address,uint256))
pushTerms((uint256,uint256,uint256)[])
EscrowCancelled(bytes20,(bool,address,address,uint256))
fillOrder((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes),uint256,bytes)
marketBuyOrders((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes)[],uint256,bytes[])
batchFillOrKillOrders((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes)[],uint256[],bytes[])

LogTokenBuilt(address,uint256,(uint192,uint192,uint160,uint64,uint32))
cancelOrder((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes))
marketSellOrders((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes)[],uint256,bytes[])
SetupDirectDebit(address,address,(uint256,uint256,uint256))
getOrdersInfo((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes)[])
matchOrders((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes),(address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes),bytes,bytes)
batchFillOrders((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes)[],uint256[],bytes[])
fillOrderNoThrow((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes),uint256,bytes)
getOrderInfo((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes))
BidSaved((address,uint256,uint256))
marketSellOrdersNoThrow((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes)[],uint256,bytes[])
marketBuyOrdersNoThrow((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes)[],uint256,bytes[])
```

**Comment by kolinko** [comment]
I just published Eveem's implementation of the ABI parser:

https://github.com/eveem-org/panoramix/blob/master/utils/supplement.py#L189

Written like crap, but well tested :)

Also, when you test, make sure that it not only parses, but produces proper signatures. I remember there were some unobvious cases with tuples/arrays when it came to calculating sha3.

**Comment by pipermerriam** [comment]
We have some existing tools to do this in `eth-abi` that are well tested.

https://eth-abi.readthedocs.io/en/latest/grammar.html

Those tools will fix issues where a single function signature is being submitted.  However, I think there is a deeper problem which is that when parsing source files, a regex is used to extract all of the function and even declarations.  I suspect that this code *might* also need to be updated.

**Comment by ligi** [comment]
I can confirm this works now after the merge of @davesque 's PR;

![Selection_099](https://user-images.githubusercontent.com/111600/88182721-d5760700-cc30-11ea-8c0f-3e947880f74c.png)
