### ISSUE TITLE
4byte.directory should link to this repo

### ISSUE THREAD

**Issue by ligi** [pipermerriam/ethereum-function-signature-registry#38]
otherwise it is hard to report errors like #37 - @kolinko would have reported this error before - but he did not find the repo. I just knew from history it is from @pipermerriam so I browsed through your repos to report the error finally..

**Comment by kolinko** [comment]
yes, please! I wanted to contact you a few months back when I bumped into these issues (and some minor ones), and found no way to do so - ended up having to build my own directory :,)

**Comment by pipermerriam** [comment]
Should be possible to add a template for the `500` error page with a link to this repository.  Django docs will have info on where that template should be and what format it should be in.

**Comment by ligi** [comment]
I think it would be great if it would not only be in the 500 page - there are also examples where one would like to open an issue - but there was no 500 before - like #39
