### ISSUE TITLE
Tuples get removed

### ISSUE THREAD

**Issue by ligi** [pipermerriam/ethereum-function-signature-registry#39]
this is similar to #37 - but it does not crash like there - but the tuple gets removed 
so when I submit setupDirectDebit(address,(uint256,uint256,uint256))
it ends up as a different signature:
![image](https://user-images.githubusercontent.com/111600/67063115-7ca8a800-f1a0-11e9-99af-c5d887fc25d7.png)

**Comment by pipermerriam** [comment]
I suspect this is a misbehaving (overmatching?) regex but that's just my gut.  will need to get in and figure out a fix for this.

**Comment by ligi** [comment]
I can confirm this works now - closing this issue. 
Thanks @davesque for the PR & @pipermerriam for merging

![Selection_097](https://user-images.githubusercontent.com/111600/88181322-f9384d80-cc2e-11ea-9ab4-166440e9547e.png)
