### ISSUE TITLE
UX: no user feedback when adding existing signature

### ISSUE THREAD

**Issue by ligi** [pipermerriam/ethereum-function-signature-registry#49]
currently when you add an existing signature you press the submit button and nothing happens. This is confusing to users. Better would be SnackBar like thing similar to the success case - just with the extra info (already existed) instead of "Added"

**Comment by pipermerriam** [comment]
This would be the place to start if someone wants to work on this

https://github.com/pipermerriam/ethereum-function-signature-registry/blob/def6c03daea61c4fdb7c159bb236997aa3f2672b/func_sig_registry/registry/views.py#L85-L97

**Comment by ayanginet** [comment]
I am rewriting this part now, so I will keep in mind this issue.
