### ISSUE TITLE
nginx server shows default page

### ISSUE THREAD

**Issue by xoryouyou** [pipermerriam/ethereum-function-signature-registry#50]
### What is wrong?

http://www.4byte.directory/ seems to be defaulting to the standard nginx page.

The webserver is revealing its version `nginx/1.14.2` which is quite dated (Dec 2018).

### How can it be fixed

* Update nginx
* Fix nginx configuration.
* consider setting [`server_tokens off;` ](https://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens) to not reveal it's version and prevent automated attacks.

**Comment by pipermerriam** [comment]
Should be fixed now.  http -> https redirect was borked.  Seems to be fixed now.  Thanks for reporting.
