### ISSUE TITLE
GithubWebhookAPIView does not look for events

### ISSUE THREAD

**Issue by Nurts** [pipermerriam/ethereum-function-signature-registry#76]
### What is wrong?
* GithubWebhookAPIView does not parse events

### How can it be fixed
Option 1:
* Add `EventSignature.import_from_github_repository(login_or_name, repository, branch)` to https://github.com/pipermerriam/ethereum-function-signature-registry/blob/19e582411af16d6e9bbe5665abfe99ee63b27bcb/func_sig_registry/registry/tasks.py#L20

Option 2:
* Change https://github.com/pipermerriam/ethereum-function-signature-registry/blob/19e582411af16d6e9bbe5665abfe99ee63b27bcb/func_sig_registry/registry/tasks.py#L20 so that it looks for solidity files inside repository and calls `Signature.import_from_solidity_file(file_obj)` and `EventSignature.import_from_solidity_file(file_obj)`.
* https://github.com/pipermerriam/ethereum-function-signature-registry/blob/19e582411af16d6e9bbe5665abfe99ee63b27bcb/func_sig_registry/registry/models.py#L127 will become obsolete.

**Comment by pipermerriam** [comment]
@Nurts I'm fine with either of these. I'll leave it to you to figure out which one is appropriate.
